### ISSUE TITLE
Field list does not update when primary is selected

### ISSUE THREAD

**Issue by dylanmcreynolds** [Xi-CAM/Xi-cam.CatalogViewer#12]
I have a run that has the following stream/field combo:

{'primary': ['raw'], 
'thumbnails': ['256_jpg', '256_tiff']}

When I load the run in the Catalog Viewer, and switch from "primary" to "thumbnails", the field selector does not update. and exception is thrown (below).

```

/home/dylan/work/xicam/Xi-cam/xicam/core/msg/__init__.py:264: UserWarning: Custom loggername is no longer supported, ignored.
  warnings.warn("Custom loggername is no longer supported, " "ignored.")
Tue May 26 16:31:23 2020 - logError - ERROR - MainThread > 
 The following error was handled safely by Xi-cam. It is displayed here for debugging.
Tue May 26 16:31:23 2020 - logError - ERROR - MainThread > 
 Traceback (most recent call last):
   File "/home/dylan/work/xicam/env/lib/python3.8/site-packages/xarray/core/dataset.py", line 1164, in _construct_dataarray
    variable = self._variables[name]
 KeyError: '256_jpg'
 
During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/dylan/work/xicam/Xi-cam/xicam/gui/widgets/imageviewmixins.py", line 747, in setStream
    super(FieldSelector, self).setStream(stream_name)
   File "/home/dylan/work/xicam/Xi-cam/xicam/gui/widgets/imageviewmixins.py", line 641, in setStream
    self._updateCatalog()
   File "/home/dylan/work/xicam/Xi-cam/xicam/gui/widgets/imageviewmixins.py", line 625, in _updateCatalog
    eventStream = stream.to_dask()[self.field]
   File "/home/dylan/work/xicam/env/lib/python3.8/site-packages/xarray/core/dataset.py", line 1254, in __getitem__
    return self._construct_dataarray(key)
   File "/home/dylan/work/xicam/env/lib/python3.8/site-packages/xarray/core/dataset.py", line 1166, in _construct_dataarray
    _, name, variable = _get_virtual_variable(
   File "/home/dylan/work/xicam/env/lib/python3.8/site-packages/xarray/core/dataset.py", line 167, in _get_virtual_variable
    ref_var = variables[ref_name]
 KeyError: '256_jpg'
```

**Comment by ronpandolfi** [comment]
@dylanmcreynolds Hm, I have a dataset with 2 streams + 2 fields each, and I'm able to switch between them. Is that catalog somewhere I can access it, or can you send me a connection config?

Edit: Nvm, I can reproduce it now if the field names are different in each stream.

**Comment by ronpandolfi** [comment]
This should do it; feel free to merge/close if it works for you.
https://github.com/Xi-CAM/Xi-cam/pull/4

**Comment by dylanmcreynolds** [comment]
This is fixed. Thanks!
